export const marques = [
    { label: "autre", name: "autre" },
    { label: "mercedes", name: "mercedes" }, 
    { label: "citroen", name: "citroen" },
    { label: "audi", name: "audi" },
    { label: "BMW", name: "BMW" },
    { label: "chevrolet", name: "chevrolet" },
    { label: "chrystler", name: "chrystler" },
    { label: "alpha romeo", name: "alpha romeo" },
    { label: "cupra", name: "cupra" },
    { label: "dacia", name: "dacia" },
    { label: "dodge", name: "dodge" },
    { label: "ferrari", name: "ferrari" },
    { label: "fiat", name: "fiat" },
    { label: "ford", name: "ford" },
    { label: "hummer", name: "hummer" },
    { label: "hyundai", name: "hyundai" },
    { label: "infiniti", name: "infiniti" },
    { label: "jaguar", name: "jaguar" },
    { label: "jeep", name: "jeep" },
    { label: "kia", name: "kia" },
    { label: "lada", name: "lada" },
    { label: "lamborghini", name: "lamborghini" },
    { label: "land rover", name: "land rover" },
    { label: "lexus", name: "lexus" },
    { label: "lotus", name: "lotus" },
    { label: "mazda", name: "mazda" },
    { label: "mclaren", name: "mclaren" },
    { label: "MG", name: "MG" },
    { label: "mini", name: "mini" },
    { label: "mitsubishi", name: "mitsubishi" },
    { label: "nissan", name: "nissan" },
    { label: "opel", name: "opel" },
    { label: "peugeot", name: "peugeot" },
    { label: "opel", name: "opel" },
    { label: "porsche", name: "porsche" },
    { label: "renault", name: "renault" },
    { label: "rolls royce", name: "rolls royce" },
    { label: "seat", name: "seat" },
    { label: "skoda", name: "skoda" },
    { label: "smart", name: "smart" },
    { label: "suzuki", name: "suzuki" },
    { label: "tesla", name: "tesla" },
    { label: "toyota", name: "toyota" },
    { label: "volvo", name: "volvo" },
    { label: "volkswagen", name: "volkswagen" },
];

export const couleurs=[
    { label: "autre", name: "autre" }, 
    { label: "rouge", name: "rouge" }, 
    { label: "vert", name: "vert" }, 
    { label: "bleu", name: "bleu" }, 
    { label: "jaune", name: "jaune" }, 
    { label: "blanc", name: "blanc" }, 
    { label: "gris", name: "gris" }, 
    { label: "noir", name: "noir" }, 
    { label: "orange", name: "orange" }, 
    { label: "maron", name: "maron" }
];